//
//  Strings.swift
//  BettingHub
//
//  Created by Maxim Bezdenezhnykh on 15.04.2020.
//  Copyright © 2020 Maxim Bezdenezhnykh. All rights reserved.
//

import Foundation 

class Text {
    static var loginTitle: String { "loginTitle".localized }
    static var registerTitle: String { "registerTitle".localized }
    static var restoreTitle: String { "restoreTitle".localized }
    static var yourNickname: String { "yourNickname".localized }
    static var yourMail: String { "yourMail".localized }
    static var yourMailOrNick: String { "yourMailOrNick".localized }
    static var password: String { "password".localized }
    static var confirmPass: String { "confirmPass".localized }
    static var login: String { "login".localized }
    static var restore: String { "restore".localized }
    static var or: String { "or".localized }
    static var loginWithGoogle: String { "loginWithGoogle".localized }
    static var withGoogle: String { "withGoogle".localized }
    static var forgetPass: String { "forgetPass".localized }
    static var noAccount: String { "noAccount".localized }
    static var haveAccount: String { "haveAccount".localized }
    static var register: String { "register".localized }
    static var authorize: String { "authorize".localized }
    static var wrongLogin: String { "wrongLogin".localized }
    static var back: String { "back".localized }
    static var BANK: String { "BANK".localized }
    static var topForecasters: String { "topForecasters".localized }
    static var showAll: String { "showAll".localized }
    static var showMore: String { "showMore".localized }
    static var bookmakersRating: String { "bookmakersRating".localized }
    static var firm: String { "firm".localized }
    static var rating: String { "rating".localized }
    static var bonus: String { "bonus".localized }
    static var review: String { "review".localized }
    static var date: String { "date".localized }
    static var match: String { "match".localized }
    static var bets: String { "bets".localized }
    static var topMatches: String { "topMatches".localized }
    static var forecast: String { "forecast".localized }
    static var betAmount: String { "betAmount".localized }
    static var matchStart: String { "matchStart".localized }
    static var coeficient: String { "coeficient".localized }
    static var income: String { "income".localized }
    static var lastForecasts: String { "lastForecasts".localized }
    static var FORECASTS: String { "FORECASTS".localized }
    static var subscribtions: String { "subscribtions".localized }
    static var allForecasts: String { "allForecasts".localized }
    static var paid: String { "paid".localized }
    static var nearest: String { "nearest".localized }
    static var all: String { "all".localized }
    static var football: String { "football".localized }
    static var tennis: String { "tennis".localized }
    static var basketball: String { "basketball".localized }
    static var hockey: String { "hockey".localized }
    static var other: String { "other".localized }
    static var subscribe: String { "subscribe".localized }
    static var unsubscibe: String { "unsubscibe".localized }
    static var tournament: String { "tournament".localized }
    static var dateTime: String { "dateTime".localized }
    static var forecastWord: String { "forecastWord".localized }
    static var coeficientWord: String { "coeficientWord".localized }
    static var bet: String { "bet".localized }
    static var possibleWin: String { "possibleWin".localized }
    static var reply: String { "reply".localized }
    static var menuMatches: String { "menuMatches".localized }
    static var menuBookmakers: String { "menuBookmakers".localized }
    static var menuForecasters: String { "menuForecasters".localized }
    static var menuNews: String { "menuNews".localized }
    static var menuArticles: String { "menuArticles".localized }
    static var fieldsEmptyError: String { "fieldsEmptyError".localized }
    static var unmatchingPasswordsError: String { "unmatchingPasswordsError".localized }
    static var unspecifiedError: String { "unspecifiedError".localized }
    static var month: String { "month".localized }
    static var allTime: String { "allTime".localized }
    static var forecastersRating: String { "forecastersRating".localized }
    static var name: String { "name".localized }
    static var incomeWord: String { "incomeWord".localized }
    static var forecasts: String { "forecasts".localized }
    static var statistics: String { "statistics".localized }
    static var favorites: String { "favorites".localized }
    static var wins: String { "wins".localized }
    static var loses: String { "loses".localized }
    static var draws: String { "draws".localized }
    static var subscribers: String { "subscribers".localized }
    static var place: String { "place".localized }
    static var netProfit: String { "netProfit".localized }
    static var roiAllTime: String { "roiAllTime".localized }
    static var legendWins: String { "legendWins".localized }
    static var legendLoses: String { "legendLoses".localized }
    static var legendDraws: String { "legendDraws".localized }
    static var profileStatsROI: String { "profileStatsROI".localized }
    static var profileStatsNetProfit: String { "profileStatsNetProfit".localized }
    static var profileStatsPassing: String { "profileStatsPassing".localized }
    static var profileStatsCoefficient: String { "profileStatsCoefficient".localized }
    static var profileStatsForecasts: String { "profileStatsForecasts".localized }
    static var rateApp: String { "rateApp".localized }
    static var settingsPersonalData: String { "settingsPersonalData".localized }
    static var settingsAttachedAccounts: String { "settingsAttachedAccounts".localized }
    static var settingsChangePassword: String { "settingsChangePassword".localized }
    static var newPassword: String { "newPassword".localized }
    static var settingsSaveChanges: String { "settingsSaveChanges".localized }
    static var settingsNotifications: String { "settingsNotifications".localized }
    static var settingsEmailNotifications: String { "settingsEmailNotifications".localized }
    static var settingsPushNotifications: String { "settingsPushNotifications".localized }
    static var settingsReplies: String { "settingsReplies".localized }
    static var exit: String { "exit".localized }
    static var bookmakerFirm: String { "bookmakerFirm".localized }
    static var site: String { "site".localized }
    static var line: String { "line".localized }
    static var reliability: String { "reliability".localized }
    static var payingSystems: String { "payingSystems".localized }
    static var topBets: String { "topBets".localized }
    static var forecaster: String { "forecaster".localized }
    static var passability: String { "passability".localized }
    static var userAlreadyRegisteredText: String { "userAlreadyRegisteredText".localized }
    static var notSuitablePasswordText: String { "notSuitablePasswordText".localized }
    static var notSuitableLoginText: String { "notSuitableLoginText".localized }
    static var confidentialPolitics: String { "confidentialPolitics".localized }
    static var leaveFeedback: String { "leaveFeedback".localized }
    static var soon: String { "soon".localized }
    static var noBets: String { "noBets".localized }
    static var comments: String { "comments".localized }
    static var articles: String { "articles".localized }
    static var similarArticles: String { "similarArticles".localized }
}

